version: "3"

services:
  vote:
    image: ${REGISTRY}quiz-voting:${SHA_COMMIT}
    ports:
      - "81:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
      - EVENT_STORE_MANAGER_HOST=eventstore:2113
  
  results:
    image: ${REGISTRY}quiz-results:${SHA_COMMIT}
    ports:
      - "82:80"
    environment: 
      - EVENT_STORE=tcp://admin:changeit@eventstore:1113
 
  ui:
    image: ${REGISTRY}quiz-ui:${SHA_COMMIT}
    depends_on:
      - vote
      - results
    ports:
      - "80:5000"

  setup:
    image: ${REGISTRY}quiz-setup:${SHA_COMMIT}
    depends_on:
      - eventstore
    environment: 
      - EVENT_STORE_MANAGER_HOST=eventstore:2113

  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
